config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :contacts do
    collection do
      get 'search'
    end
  end

  resources :artists do
    collection do
      get 'search'
    end
  end

  resources :labels do
    collection do
      get 'search'
    end
  end

  resources :albums do
    collection do
      get 'search'
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Root Route
  root 'albums#index'
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :label
  has_and_belongs_to_many :artists

  validates :label_id, presence: true
  validates :year, presence: true, length: {maximum: 4, minimum: 4}
  validates :title, presence: true, length: {maximum: 250, minimum: 3}
  validates :genre, presence: true, length: {maximum: 250, minimum: 3}
  validates :plays, presence: true, length: {maximum: 10, minimum: 1}
  validates :artist_ids, presence: true
end

app/models/albums_artists.rb
class AlbumsArtists < ApplicationRecord
  belongs_to :album
  belongs_to :artist
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_and_belongs_to_many :albums

  # Validations
  validates :name, length: { minimum: 3, maximum: 255 }, presence: true
  validates :name, uniqueness: true
  validates :started, numericality:{greater_than_or_equal_to: 1}, presence: true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :albums

  # Validations
  validates :name, length: {minimum: 5, maximum: 50}, presence: true
  validates :name, uniqueness: true
  validates :ceo, length: {minimum: 5, maximum: 50}, presence: true
  validates :founded, numericality:{greater_than_or_equal_to: 1}, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  def search
    @albums = Album.where("title like ?", "%#{params[:q]}%")
    render :index
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
    @artist = Artist.all
  end

  # GET /albums/1/edit
  def edit
    @artist = Artist.all
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:title, :genre, :year, :plays, :label_id, :artist_ids =>[])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artist = Artist.all
  end

  def search
    @artist = Artist.where("name like ?", "%#{params[:q]}%")
    render :index
  end


  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
    @albums = Album.all
  end

  # GET /artists/1/edit
  def edit
    @albums = Album.all
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :started, :album_ids =>[])
    end
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: [:show, :edit, :update, :destroy]

  # GET /labels
  # GET /labels.json
  def index
    @labels = Label.all
  end

  def search
    @labels = Label.where("name like ?", "%#{params[:q]}%")
    render :index
  end

  # GET /labels/1
  # GET /labels/1.json
  def show
  end

  # GET /labels/new
  def new
    @label = Label.new
  end

  # GET /labels/1/edit
  def edit
  end

  # POST /labels
  # POST /labels.json
  def create
    @label = Label.new(label_params)

    respond_to do |format|
      if @label.save
        format.html { redirect_to @label, notice: 'Label was successfully created.' }
        format.json { render :show, status: :created, location: @label }
      else
        format.html { render :new }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /labels/1
  # PATCH/PUT /labels/1.json
  def update
    respond_to do |format|
      if @label.update(label_params)
        format.html { redirect_to @label, notice: 'Label was successfully updated.' }
        format.json { render :show, status: :ok, location: @label }
      else
        format.html { render :edit }
        format.json { render json: @label.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /labels/1
  # DELETE /labels/1.json
  def destroy
    @label.destroy
    respond_to do |format|
      format.html { redirect_to labels_url, notice: 'Label was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = Label.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def label_params
      params.require(:label).permit(:name, :ceo, :founded)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album, local: true) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :artist_id %><br>
    <%= form.collection_select(:artist_ids, Artist.all, :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="field">
    <%= form.label :plays %>
    <%= form.number_field :plays %>
  </div>

  <div class="field">
    <%= form.label :label_id %>
    <%= form.select(:label_id, Label.all.collect {|p| [ p.name, p.id ]}) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Albums</h1>
<%= form_tag(search_albums_url, method: 'get') do %>
  <%= csp_meta_tag %>
  <%= label_tag(:q, 'Search for:') %>
  <%= text_field_tag(:q) %>
  <%= submit_tag('Search') %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Genre</th>
      <th>Year</th>
      <th>Plays</th>
      <th>Label</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.title %></td>
        <td><%= album.genre %></td>
        <td><%= album.year %></td>
        <td><%= album.plays %></td>
        <td><%= album.label.name %></td>
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @album.title %>
</p>

<ul>
  <% @album.artists.each do |artist| %>
    <li><%= artist.name %></li>
    <% end %>
</ul>

<p>
  <strong>Genre:</strong>
  <%= @album.genre %>
</p>

<p>
  <strong>Year:</strong>
  <%= @album.year %>
</p>

<p>
  <strong>Plays:</strong>
  <%= @album.plays %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @album.artists.name %>
</p>


<p>
  <strong>Label:</strong>
  <%= @album.label.name %>
</p>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/artists/_form.html.erb
<%= form_with(model: artist, local: true) do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  </div>

  <div class="field">
  <%= form.label :started %>
  <%= form.text_field :started %>
  </div>
  </div>

  <div class="field">
    <% if Album.all != [] %>
    <%= select("album", "id", Album.all.collect {|p| [ p.title, p.id ]}) %>
    <% end %>

  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Artists</h1>
<%= form_tag(search_artists_url, method: 'get') do %>
  <%= csp_meta_tag %>
  <%= label_tag(:q, 'Search for:') %>
  <%= text_field_tag(:q) %>
  <%= submit_tag('Search') %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Started</th>
      <th>Album</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artist.each do |artist| %>
      <tr>
        <td><%= artist.name %></td>
        <td><%= artist.started %></td>
          <td>
            <% artist.albums.each do |album| %>
              <%= album.title %>
              <%= link_to album.name, artist_path(album) %>
            <% end %>
          </td>
        <td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>
<ul>
  <% @artist.albums.each do |album| %>
    <li><%= album.title %></li>
  <% end %>
</ul>

<p>
  <strong>Started:</strong>
  <%= @artist.started %>
</p>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>

app/views/labels/_form.html.erb
<%= form_with(model: label, local: true) do |form| %>
  <% if label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(label.errors.count, "error") %> prohibited this label from being saved:</h2>

      <ul>
      <% label.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :ceo %>
    <%= form.text_field :ceo %>
  </div>

  <div class="field">
    <%= form.label :founded %>
    <%= form.number_field :founded %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/labels/edit.html.erb
<h1>Editing Label</h1>

<%= render 'form', label: @label %>

<%= link_to 'Show', @label %> |
<%= link_to 'Back', labels_path %>

app/views/labels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Labels</h1>
<%= form_tag(search_labels_url, method: 'get') do %>
  <%= csp_meta_tag %>
  <%= label_tag(:q, 'Search for:') %>
  <%= text_field_tag(:q) %>
  <%= submit_tag('Search') %>
<% end %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ceo</th>
      <th>Founded</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @labels.each do |label| %>
      <tr>
        <td><%= label.name %></td>
        <td><%= label.ceo %></td>
        <td><%= label.founded %></td>

        <td><%= link_to 'Show', label %></td>
        <td><%= link_to 'Edit', edit_label_path(label) %></td>
        <td><%= link_to 'Destroy', label, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/labels/new.html.erb
<h1>New Label</h1>

<%= render 'form', label: @label %>

<%= link_to 'Back', labels_path %>

app/views/labels/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @label.name %>
</p>

<p>
  <strong>Ceo:</strong>
  <%= @label.ceo %>
</p>

<p>
  <strong>Founded:</strong>
  <%= @label.founded %>
</p>
<ol>
  <% @label.albums.each do |album| %>
    <li> <%= album.name %>
  <% end %>
</ol>

<%= link_to 'Edit', edit_label_path(@label) %> |
<%= link_to 'Back', labels_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Production</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </p>


  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>
  <footer>
    <br>

    <%= link_to 'New Album', new_album_path %>
    <%= link_to 'New Artist', new_artist_path %>
    <%= link_to 'New Label', new_label_path %>
  </footer>

</html>